---
- name: downloading elasticsearch
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.2-x86_64.rpm
    dest: /tmp/elasticsearch-7.9.2-x86_64.rpm

- name: installing elasticsearch
  yum:
    name: /tmp/elasticsearch-7.9.2-x86_64.rpm
    state: present

- name: starting elasticsearch
  service:
    name: elasticsearch
    state: started

- name: downloading kibana
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-8.4.3-x86_64.rpm
    dest: /tmp/kibana-8.4.3-x86_64.rpm

- name: installing kibana
  yum:
    name: /tmp/kibana-8.4.3-x86_64.rpm
    state: latest
    update_cache: yes

- name: start kibana
  service:
    name: kibana
    state: restarted

- name: downloading logstash
  get_url:
    url: https://artifacts.elastic.co/downloads/logstash/logstash-7.8.0.rpm
    dest: /tmp/logstash-7.8.0.rpm

- name: installing logstash
  yum:
    name: /tmp/logstash-7.8.0.rpm
    state: present

- name: starting logstash
  service:
    name: logstash
    state: restarted

